version: "3"
services: 
  nodeapp:
    build: 
      context: .
    volumes: 
      - .:/node/app
      - /node/app/node_modules
      - /node/app/build
    environment: 
      - SOMETHING=NICK
    expose:
      - 3000
    command: ["yarn", "start:prod"]

  nginx:
    build: 
      context: .
      dockerfile: DockerfileNginx
    links: 
      - nodeapp
      - memc
    ports:
      - 80:3001

  memc:
    image: memcached:1.5.12
    expose: 
      - 11211