version: "3"
services: 
  nodeapp:
    build: 
      context: .
    volumes: 
      - .:/node/app
      - /node/app/node_modules
    environment: 
      - SOMETHING=NICK
    expose:
      - 3000
    command: ["yarn", "dev"]

  nginx:
    build: 
      context: .
      dockerfile: DockerfileNginx
    links: 
      - nodeapp
    ports:
      - 80:3001