apiVersion: v1
kind: Service
metadata: 
  name: node-a-svc
  namespace: app-a
spec: 
  ports: 
     -  port: 3001
        protocol: TCP
        targetPort: 3000
  selector: 
    app: nick-app
  type: NodePort