apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: app-a
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testa
        backend:
          serviceName: node-a-svc
          servicePort: 3001