apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: app-a
  labels:
    app: nick-app
  name: nick-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nick-app
  template:
    metadata:
      labels:
        app: nick-app
    spec:
      containers:
      - image: nickdockernick/nick-node-app:v1
        name: nick-app
        ports:
        - containerPort: 3000